<?php
/**
 * Definisi Data & Metadata Halaman Error
 * Manajemen-PHP
 */

function getErrorDetails(int $code): array {
    $errors = [
        400 => [
            'code'        => 400,
            'status'      => 'Bad Request',
            'badge'       => 'HTTP 400 • Bad Request',
            'icon'        => '<i class="fa-solid fa-triangle-exclamation text-amber-400"></i>',
            'accent'      => 'amber',
            'glow_color'  => 'rgba(245, 158, 11, 0.15)',
            'border_color'=> 'border-amber-500/30',
            'badge_bg'    => 'bg-amber-500/10 border-amber-500/30 text-amber-300',
            'btn_bg'      => 'bg-amber-500 hover:bg-amber-400 text-slate-950 shadow-amber-500/20',
            'title'       => 'Permintaan Tidak Dapat Diproses',
            'subtitle'    => 'Sintaks atau parameter permintaan yang dikirim tidak valid atau telah dimanipulasi.',
            'description' => 'Server tidak dapat memahami permintaan Anda karena format data yang dikirimkan tidak sesuai dengan standar yang diharapkan oleh sistem sekolah.',
            'suggestions' => [
                'Periksa kembali data formulir atau parameter URL yang Anda masukkan.',
                'Pastikan tidak ada karakter terlarang atau query yang tidak lengkap.',
                'Bersihkan cache browser Anda atau muat ulang halaman.',
            ],
            'primary_btn' => ['label' => 'Kembali ke Sebelumnya', 'action' => 'history.back()', 'icon' => '<i class="fa-solid fa-arrow-left"></i>'],
        ],
        401 => [
            'code'        => 401,
            'status'      => 'Unauthorized',
            'badge'       => 'HTTP 401 • Unauthorized',
            'icon'        => '<i class="fa-solid fa-lock text-sky-400"></i>',
            'accent'      => 'sky',
            'glow_color'  => 'rgba(14, 165, 233, 0.15)',
            'border_color'=> 'border-sky-500/30',
            'badge_bg'    => 'bg-sky-500/10 border-sky-500/30 text-sky-300',
            'btn_bg'      => 'bg-sky-500 hover:bg-sky-400 text-slate-950 shadow-sky-500/20',
            'title'       => 'Autentikasi Diperlukan',
            'subtitle'    => 'Anda harus masuk (login) ke dalam akun terlebih dahulu untuk mengakses halaman ini.',
            'description' => 'Halaman atau fitur yang Anda tuju merupakan area terproteksi khusus civitas sekolah yang memerlukan identitas pengguna yang terverifikasi.',
            'suggestions' => [
                'Silakan login menggunakan akun Siswa, Guru, Orang Tua, Staf, atau Administrator.',
                'Jika sesi Anda telah berakhir, silakan login ulang untuk memperbarui token sesi.',
                'Hubungi staf tata usaha jika Anda belum memiliki akun resmi.',
            ],
            'primary_btn' => ['label' => 'Menuju Halaman Login', 'href' => '../auth/login.php', 'icon' => '<i class="fa-solid fa-key"></i>'],
        ],
        403 => [
            'code'        => 403,
            'status'      => 'Forbidden',
            'badge'       => 'HTTP 403 • Forbidden',
            'icon'        => '<i class="fa-solid fa-ban text-rose-500"></i>',
            'accent'      => 'rose',
            'glow_color'  => 'rgba(244, 63, 94, 0.15)',
            'border_color'=> 'border-rose-500/30',
            'badge_bg'    => 'bg-rose-500/10 border-rose-500/30 text-rose-300',
            'btn_bg'      => 'bg-rose-600 hover:bg-rose-500 text-white shadow-rose-600/20',
            'title'       => 'Akses Ditolak',
            'subtitle'    => 'Akun Anda tidak memiliki izin atau wewenang untuk membuka modul ini.',
            'description' => 'Sistem Manajemen-PHP menerapkan kontrol akses berbasis peran (RBAC). Hak akses Anda saat ini dibatasi untuk mencegah perubahan data tanpa otoritas yang sah.',
            'suggestions' => [
                'Pastikan Anda masuk dengan role akun yang sesuai (misal: Administrator atau Guru).',
                'Jika Anda merasa ini adalah kekeliruan hak akses, hubungi Administrator sistem.',
                'Kembali ke halaman dasbor utama Anda untuk mengakses menu yang tersedia.',
            ],
            'primary_btn' => ['label' => 'Kembali ke Dashboard', 'href' => '../dashboard/index.php', 'icon' => '<i class="fa-solid fa-gauge-high"></i>'],
        ],
        404 => [
            'code'        => 404,
            'status'      => 'Not Found',
            'badge'       => 'HTTP 404 • Not Found',
            'icon'        => '<i class="fa-solid fa-compass text-purple-400"></i>',
            'accent'      => 'purple',
            'glow_color'  => 'rgba(168, 85, 247, 0.15)',
            'border_color'=> 'border-purple-500/30',
            'badge_bg'    => 'bg-purple-500/10 border-purple-500/30 text-purple-300',
            'btn_bg'      => 'bg-purple-600 hover:bg-purple-500 text-white shadow-purple-600/20',
            'title'       => 'Halaman Tidak Ditemukan',
            'subtitle'    => 'Tautan yang Anda tuju mungkin telah dihapus, dipindahkan, atau alamat URL salah ketik.',
            'description' => 'Halaman atau berkas yang Anda cari tidak tersedia di server sekolah kami. Pastikan alamat URL yang dimasukkan sudah tepat atau kembali ke menu utama.',
            'suggestions' => [
                'Periksa kembali penulisan URL di bilah alamat peramban Anda.',
                'Gunakan menu navigasi resmi di dasbor untuk menemukan berkas atau halaman terkait.',
                'Gunakan tombol pencarian atau kembali ke halaman beranda.',
            ],
            'primary_btn' => ['label' => 'Kembali ke Beranda', 'href' => '../index.php', 'icon' => '<i class="fa-solid fa-house"></i>'],
        ],
        419 => [
            'code'        => 419,
            'status'      => 'Page Expired',
            'badge'       => 'HTTP 419 • Page Expired',
            'icon'        => '<i class="fa-solid fa-hourglass-half text-orange-400"></i>',
            'accent'      => 'orange',
            'glow_color'  => 'rgba(249, 115, 22, 0.15)',
            'border_color'=> 'border-orange-500/30',
            'badge_bg'    => 'bg-orange-500/10 border-orange-500/30 text-orange-300',
            'btn_bg'      => 'bg-orange-500 hover:bg-orange-400 text-slate-950 shadow-orange-500/20',
            'title'       => 'Sesi Formulir Kadaluarsa',
            'subtitle'    => 'Token keamanan CSRF Anda telah kadaluarsa karena halaman dibiarkan terlalu lama.',
            'description' => 'Untuk melindungi akun dan transaksi data sekolah Anda dari serangan Cross-Site Request Forgery (CSRF), token sesi otomatis dihanguskan setelah beberapa saat tidak aktif.',
            'suggestions' => [
                'Muat ulang (refresh) halaman ini lalu kirimkan kembali formulir Anda.',
                'Jangan biarkan formulir ujian atau pengajuan surat terbuka terlalu lama tanpa aktivitas.',
                'Pastikan cookie browser diaktifkan agar sesi keamanan berjalan normal.',
            ],
            'primary_btn' => ['label' => 'Muat Ulang Halaman', 'action' => 'location.reload()', 'icon' => '<i class="fa-solid fa-rotate-right"></i>'],
        ],
        500 => [
            'code'        => 500,
            'status'      => 'Internal Server Error',
            'badge'       => 'HTTP 500 • Internal Error',
            'icon'        => '<i class="fa-solid fa-server text-rose-500"></i>',
            'accent'      => 'red',
            'glow_color'  => 'rgba(239, 68, 68, 0.15)',
            'border_color'=> 'border-red-500/30',
            'badge_bg'    => 'bg-red-500/10 border-red-500/30 text-red-300',
            'btn_bg'      => 'bg-red-600 hover:bg-red-500 text-white shadow-red-600/20',
            'title'       => 'Terjadi Kesalahan di Server',
            'subtitle'    => 'Sistem mengalami kendala saat memproses permintaan Anda.',
            'description' => 'Server kami mendeteksi masalah internal yang tidak terduga. Insiden ini telah otomatis dicatat di log sistem untuk segera diinvestigasi oleh tim pengembang.',
            'suggestions' => [
                'Tunggu beberapa saat kemudian muat ulang halaman.',
                'Kembali ke halaman dasbor utama dan coba kembali aksi Anda.',
                'Bila masalah terus berulang, laporkan kendala ke administrator IT sekolah.',
            ],
            'primary_btn' => ['label' => 'Coba Muat Ulang', 'action' => 'location.reload()', 'icon' => '<i class="fa-solid fa-rotate-right"></i>'],
        ],
        503 => [
            'code'        => 503,
            'status'      => 'Service Unavailable',
            'badge'       => 'HTTP 503 • Service Unavailable',
            'icon'        => '<i class="fa-solid fa-screwdriver-wrench text-emerald-400"></i>',
            'accent'      => 'emerald',
            'glow_color'  => 'rgba(168, 85, 247, 0.15)',
            'border_color'=> 'border-emerald-500/30',
            'badge_bg'    => 'bg-emerald-500/10 border-emerald-500/30 text-emerald-300',
            'btn_bg'      => 'bg-emerald-600 hover:bg-emerald-500 text-white shadow-emerald-600/20',
            'title'       => 'Pemeliharaan Sistem Sedang Berlangsung',
            'subtitle'    => 'Layanan Manajemen-PHP sementara waktu sedang dalam proses optimalisasi atau pemeliharaan server.',
            'description' => 'Kami sedang melakukan pembaruan rutin untuk meningkatkan kecepatan, keandalan, dan keamanan sistem sekolah. Layanan akan segera aktif kembali dalam waktu dekat.',
            'suggestions' => [
                'Silakan periksa kembali dalam beberapa menit.',
                'Data akademik, presensi, dan ujian Anda tetap aman di basis data.',
                'Hubungi narahubung sekolah jika Anda membutuhkan penanganan administrasi darurat.',
            ],
            'primary_btn' => ['label' => 'Periksa Lagi Sekarang', 'action' => 'location.reload()', 'icon' => '<i class="fa-solid fa-rotate-right"></i>'],
        ],
    ];

    return $errors[$code] ?? [
        'code'        => $code,
        'status'      => 'Unknown Error',
        'badge'       => "HTTP $code • Error",
        'icon'        => '<i class="fa-solid fa-triangle-exclamation text-slate-400"></i>',
        'accent'      => 'slate',
        'glow_color'  => 'rgba(148, 163, 184, 0.15)',
        'border_color'=> 'border-slate-500/30',
        'badge_bg'    => 'bg-slate-500/10 border-slate-500/30 text-slate-300',
        'btn_bg'      => 'bg-blue-600 hover:bg-blue-500 text-white shadow-blue-600/20',
        'title'       => 'Terjadi Kesalahan Tak Terduga',
        'subtitle'    => 'Kode status respons: ' . $code,
        'description' => 'Permintaan Anda mengalami gangguan yang belum terdefinisi secara spesifik oleh sistem.',
        'suggestions' => [
            'Kembali ke halaman utama untuk melanjutkan penjelajahan.',
            'Muat ulang halaman untuk mencoba kembali.',
        ],
        'primary_btn' => ['label' => 'Kembali ke Beranda', 'href' => '../index.php', 'icon' => '<i class="fa-solid fa-house"></i>'],
    ];
}

